project: LowRoller.xcodeproj
schemes: [LowRoller]
targets: [LowRoller]
configuration: Debug
format: xcode
clean_build: false

# Be more aggressive:
retain_public: false
retain_assign_only_properties: true

# Ignore previews/generated:
excluded:
  - "**/*Preview*.swift"
  - "**/Generated/**/*"
