# .periphery.yml — Periphery 3.x
project: LowRoller.xcodeproj
schemes:
  - LowRoller

retain_public: true
retain_assign_only_properties: true

# Keep test targets & previews out of analysis
exclude_targets:
  - LowRollerTests
  - LowRollerUITests

report_exclude:
  - "**/Generated/**"
  - "**/*Previews.swift"
  - "**/Previews/**"
  - "**/*Tests*/**"
