project: LowRoller/LowRoller.xcodeproj
schemes:
  - LowRoller
format: xcode
clean_build: true
build_arguments:
  - -sdk
  - iphonesimulator
  - -destination
  - platform=iOS Simulator,name=iPhone 17 Pro,OS=26.0

# App, not a framework → don't retain public symbols by default.
retain_public: false

# Keep properties/members that are only touched via Codable synthesis.
retain_codable_properties: true

# Optional noise trims
report_exclude:
  - "**/Generated/**"
  - "**/*.g.swift"
