[package]
name = "low_roller_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "low_roller_engine"
path = "src/lib.rs"

[dependencies]
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
